site_name: Ushka Framework
site_url: https://kleber-code.github.io/ushka
repo_url: https://github.com/kleber-code/ushka
repo_name: kleber-code/ushka
edit_uri: ""

nav:
    - "Home": index.md
    - "Features": features.md
    - "Guide":
          - "Introduction": "guide/index.md"
          - "Configuration": "guide/configuration.md"
          - "Routing": "guide/routing.md"
          - "Templates": "guide/templates.md"
          - "Static Files": "guide/static_files.md"
          - "ORM": "guide/orm.md"
          - "CLI": "guide/cli.md"
          - "Dependency Injection": "guide/dependency_injection.md"
          - "Flashing": "guide/flashing.md"
          - "Error Handling": "guide/error_handling.md"
    - "Tutorials":
          - "Getting Started": "tutorials/index.md"
          - "Simple API": "guide/tutorial_simple_api.md"
    - "Roadmap": roadmap.md
    - API Reference:
        - Ushka:
            - Cli:
                - Commands:
                    - Db: api/ushka/cli/commands/db.md
                    - Dev: api/ushka/cli/commands/dev.md
                    - New: api/ushka/cli/commands/new.md
                    - Routes: api/ushka/cli/commands/routes.md
                    - Run: api/ushka/cli/commands/run.md
            - Core:
                - App: api/ushka/core/app.md
                - Config: api/ushka/core/config.md
                - Error Handler: api/ushka/core/error_handler.md
                - Exceptions: api/ushka/core/exceptions.md
                - Log: api/ushka/core/log.md
                - Router: api/ushka/core/router.md
            - Http:
                - Cookies: api/ushka/http/cookies.md
                - Error: api/ushka/http/error.md
                - Exceptions: api/ushka/http/exceptions.md
                - Multipart: api/ushka/http/multipart.md
                - Redirect: api/ushka/http/redirect.md
                - Request: api/ushka/http/request.md
                - Response: api/ushka/http/response.md
                - Sessions: api/ushka/http/sessions.md
            - Orm:
                - Database: api/ushka/orm/database.md
            - Static:
                - Files: api/ushka/static/files.md
            - Templating:
                - Engine: api/ushka/templating/engine.md
            - Utils:
                - Flash: api/ushka/utils/flash.md

theme:
    name: material
    logo: assets/logo.jpg
    favicon: assets/favicon/favicon.ico

    palette: 
      - scheme: default
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode

      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
    
    features:
        - navigation.tabs
        - navigation.sections
        - navigation.top
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
        - search.suggest
    icon:
        repo: fontawesome/brands/github

extra:
    version:
        provider: mike
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/kleber-code
        - icon: fontawesome/brands/python
          link: https://pypi.org/project/ushka/
    manifest: "assets/favicon/site.webmanifest"

extra_css:
    - assets/custom.css

markdown_extensions:
    - admonition
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - toc:
          permalink: true
plugins:
    - termynal
    - optimize
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [src]
                options:
                    docstring_style: numpy
